name: docker-clang

on:
  push:
    branches:
    - 'main'
    - 'master'
    - 'dev'
    paths-ignore:
    - '**/README.md'
  pull_request:
    branches:
    - '*'
  schedule:
  - cron:  "0 0 1 * *"
  workflow_dispatch:

jobs:
  image:
    name: docker-clang ${{ matrix.version }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version: ["3.3", "3.4", "3.4", "3.5", "3.7", "3.8", "3.9", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "dev", "latest"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Build image
        run: docker build . -f ${{ matrix.version }}.Dockerfile -t silkeh/clang:${{ matrix.version }}
      - name: Run tests
        run: docker run --rm -v "$PWD:/build" silkeh/clang:${{ matrix.version }} /build/tests/run.sh
